<script setup>
import axios from 'axios';
import { computed, onMounted, reactive, ref } from 'vue';
const state = reactive({ leases: [], obligations: [], payments: [], notifications: [] });
const loading = ref(true); const error = ref(''); const provider = ref('stripe');
const money = cents => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN' }).format(Number(cents || 0) / 100);
const due = computed(() => state.obligations.filter(o => !['paid', 'void'].includes(o.status)));
async function load() { try { const { data } = await axios.get('/api/tenant/state'); Object.assign(state, data, { leases: data.leases?.data || data.leases, obligations: data.obligations?.data || data.obligations }); } catch (e) { error.value = e.response?.data?.message || 'Brak dostępu.'; } finally { loading.value = false; } }
async function pay(item) { try { const { data } = await axios.post(`/api/tenant/obligations/${item.id}/checkout`, { provider: provider.value }); window.location.assign(data.checkout_url); } catch (e) { error.value = e.response?.data?.message || 'Nie udało się rozpocząć płatności.'; } }
async function readAll() { await axios.post('/api/tenant/notifications/read'); await load(); }
onMounted(load);
</script>
<template><main class="tenant-shell"><header class="tenant-header"><a href="/" class="app-brand"><span class="brand-mark">L</span> LokalPay Pro</a><span>Portal najemcy</span></header><div class="container py-5"><div v-if="loading" class="spinner-border"></div><div v-if="error" class="alert alert-danger">{{ error }}</div><template v-if="!loading"><section class="tenant-welcome"><div><small>TWÓJ NAJEM</small><h1>{{ state.leases[0]?.property_name || 'Portal najemcy' }}</h1><p>Wszystkie należności i potwierdzone wpłaty w jednym miejscu.</p></div><div><small>DO ZAPŁATY</small><strong>{{ money(due.reduce((s,o)=>s+o.remaining_cents,0)) }}</strong></div></section><div class="row g-4 mt-2"><div class="col-lg-8"><article class="panel-card"><div class="d-flex justify-content-between align-items-center"><h2>Należności</h2><select v-model="provider" class="form-select provider-select"><option value="stripe">Stripe</option><option value="payu">PayU</option></select></div><div v-for="o in state.obligations" :key="o.id" class="tenant-obligation"><div><b>{{ o.period }} · {{ o.property_name }}</b><small>Termin: {{ o.due_date }}</small></div><strong>{{ money(o.remaining_cents) }}</strong><span class="badge text-bg-light">{{ o.status }}</span><button v-if="!['paid','void'].includes(o.status)" class="btn btn-lime btn-sm" @click="pay(o)">Zapłać</button></div></article><article class="panel-card mt-4"><h2>Historia płatności</h2><div class="table-responsive"><table class="table"><thead><tr><th>Data</th><th>Źródło</th><th>Kwota</th></tr></thead><tbody><tr v-for="p in state.payments" :key="p.id"><td>{{ p.paid_on }}</td><td>{{ p.source }}</td><td>{{ money(p.amount_cents) }}</td></tr></tbody></table></div></article></div><div class="col-lg-4"><article class="panel-card"><div class="d-flex justify-content-between"><h2>Powiadomienia</h2><button class="btn btn-sm btn-link" @click="readAll">Przeczytane</button></div><div v-for="n in state.notifications" :key="n.id" class="notification-row"><i class="bi bi-bell"></i><div><b>{{ n.data?.title }}</b><p>{{ n.data?.body }}</p></div></div><p v-if="!state.notifications.length">Brak wiadomości.</p></article></div></div></template></div></main></template>
